---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint
        verbose: true # create awareness of linter findings
        args: ["-d", "{extends: relaxed, rules: {line-length: {max: 120}}}"]
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    - id: black
      language_version: python
      args: [--line-length=120, --quiet]
